[environment]
port = 8080
prefix = "/u8vd7ya2t3p"

[database]
host = "localhost"
username = "root"
password = "root"
dbname = "affdb"
port = 3305

[jwt]
secret_key = "SXm9V}9kmh4%&Q\B>[V;&fH2}y69>c2ER$_^3V_$4XAs_hS'~=S6\/q.`OP;$@emTa`cM[7?E?er`N-_zxSg`7,:zt2<}7`RX\T\'g%^=)j:e?#vcmB@9`&.pz9d>5U"