[environment]
port = 8080
prefix = "/u8vd7ya2t3p"
uploads_dir = "http://54.201.86.220/api/uploads"
sub_path = "/api"

[database]
host = "localhost"
username = "root"
password = "root"
dbname = "affdb"
port = 3305

[jwt]
secret_key = "GUNP3Dqs5VFtNDrWnTGtBC4Ph7vYV8SrFMBeeVVJgXkbuVdUCub97BmDkjzG9Q8XNfTEwD4yQEgTYmCQ7Mc6y4pUSX9Gmft2M7CZ2SfDEY2Zp2fS79gD19RUAWEnM2d"